## The the input files to this notebook are retrieved from this repo: https://github.com/aybugealtay/OntoXRefExtractor

### Bruce provided renal-system-specific (http://purl.obolibrary.org/obo/UBERON_0001008) anatomical structures: https://grlc.io/api-git/hubmapconsortium/ccf-grlc/subdir/hra/as-parts.csv?location=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001008 --> this files is stored as renal_sytem_AS.csv



#### organize the results as subject/predicate/object/source format and subset them to kidney:

In [1]:
import pandas as pd

### uberon links

In [2]:
all_uberon_xlinks = pd.read_csv('../../data/outputs/hpo_to_uberon_links.csv', index_col=None)
all_uberon_xlinks

,HPO_IRI,HPO_Label,Property,Filler_IRI,Filler_Label,Obsolete,Replacement_IRI,Replacement_Label
0,http://purl.obolibrary.org/obo/HP_0000002,Abnormality of body height,characteristic of,http://purl.obolibrary.org/obo/UBERON_0000468,multicellular organism,False,NaN,NaN
1,http://purl.obolibrary.org/obo/HP_0000003,Multicystic kidney dysplasia,part of,http://purl.obolibrary.org/obo/UBERON_0002113,kidney,False,NaN,NaN
2,http://purl.obolibrary.org/obo/HP_0000003,Multicystic kidney dysplasia,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0002113,kidney,False,NaN,NaN
3,http://purl.obolibrary.org/obo/HP_0000003,Multicystic kidney dysplasia,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0011143,upper urinary tract,False,NaN,NaN
4,http://purl.obolibrary.org/obo/HP_0000003,Multicystic kidney dysplasia,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0001008,renal system,False,NaN,NaN
...,...,...,...,...,...,...,...,...
121622,http://purl.obolibrary.org/obo/HP_6001337,White appearance of duodenal mucosa,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0002114,duodenum,False,NaN,NaN
121623,http://purl.obolibrary.org/obo/HP_6001337,White appearance of duodenal mucosa,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0002108,small intestine,False,NaN,NaN
121624,http://purl.obolibrary.org/obo/HP_6001337,White appearance of duodenal mucosa,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0000160,intestine,False,NaN,NaN
121625,http://purl.obolibrary.org/obo/HP_6001337,White appearance of duodenal mucosa,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0005409,alimentary part of gastrointestinal system,False,NaN,NaN
121626,http://purl.obolibrary.org/obo/HP_6001337,White appearance of duodenal mucosa,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0001007,digestive system,False,NaN,NaN

In [3]:
all_uberon_xlinks_uberon = all_uberon_xlinks[all_uberon_xlinks['Filler_Label'].str.contains('kidney', case=False, na=False)]

In [4]:
len(all_uberon_xlinks['Filler_IRI'].unique())

1287

In [5]:
Filler_Label_df = all_uberon_xlinks['Filler_Label'].to_frame().drop_duplicates().reset_index(drop=True)
Filler_Label_df.to_csv('../../data/outputs/hpo_to_cl_links_unique_filler_labels.csv', index=False)

In [21]:
renal_system_as = pd.read_csv('../../data/renal_system_AS.csv', index_col=None)
renal_system_as

,part_iri,part_label
0,http://purl.obolibrary.org/obo/UBERON_0000056,ureter
1,http://purl.obolibrary.org/obo/UBERON_0000074,renal glomerulus
2,http://purl.obolibrary.org/obo/UBERON_0000362,renal medulla
3,http://purl.obolibrary.org/obo/UBERON_0000381,urinary bladder detrusor smooth muscle
4,http://purl.obolibrary.org/obo/UBERON_0001008,renal system
...,...,...
89,http://purl.obolibrary.org/obo/UBERON_8600036,kidney loop of Henle long descending thin limb...
90,http://purl.obolibrary.org/obo/UBERON_8600037,kidney loop of Henle long descending thin limb...
91,https://purl.org/ccf/ASCTB-TEMP_kidney-lymphat...,Kidney Lymphatic Vessel
92,https://purl.org/ccf/ASCTB-TEMP_papillary-tip-...,Papillary Tip Epithelium
93,https://purl.org/ccf/ASCTB-TEMP_ureter-vascula...,ureter vasculature

In [24]:
# Filter the DataFrame using the pattern
all_uberon_xlinks_kidney = all_uberon_xlinks[
    all_uberon_xlinks['Filler_IRI'].isin(renal_system_as['part_iri'].tolist())
]
all_uberon_xlinks_kidney

,HPO_IRI,HPO_Label,Property,Filler_IRI,Filler_Label,Obsolete,Replacement_IRI,Replacement_Label
1,http://purl.obolibrary.org/obo/HP_0000003,Multicystic kidney dysplasia,part of,http://purl.obolibrary.org/obo/UBERON_0002113,kidney,False,NaN,NaN
2,http://purl.obolibrary.org/obo/HP_0000003,Multicystic kidney dysplasia,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0002113,kidney,False,NaN,NaN
3,http://purl.obolibrary.org/obo/HP_0000003,Multicystic kidney dysplasia,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0011143,upper urinary tract,False,NaN,NaN
4,http://purl.obolibrary.org/obo/HP_0000003,Multicystic kidney dysplasia,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0001008,renal system,False,NaN,NaN
12,http://purl.obolibrary.org/obo/HP_0000009,Functional abnormality of the bladder,characteristic of,http://purl.obolibrary.org/obo/UBERON_0001255,urinary bladder,False,NaN,NaN
...,...,...,...,...,...,...,...,...
121367,http://purl.obolibrary.org/obo/HP_6001294,Tubular accumulation of uromodulin,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0011143,upper urinary tract,False,NaN,NaN
121368,http://purl.obolibrary.org/obo/HP_6001294,Tubular accumulation of uromodulin,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0001008,renal system,False,NaN,NaN
121618,http://purl.obolibrary.org/obo/HP_6001336,Hairy kidney sign,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0002113,kidney,False,NaN,NaN
121619,http://purl.obolibrary.org/obo/HP_6001336,Hairy kidney sign,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0011143,upper urinary tract,False,NaN,NaN
121620,http://purl.obolibrary.org/obo/HP_6001336,Hairy kidney sign,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0001008,renal system,False,NaN,NaN

In [25]:
hpo_asct_kidney_edges = all_uberon_xlinks_kidney[['HPO_IRI','Property','Filler_IRI']]
hpo_asct_kidney_edges['predicate'] = 'https://purl.humanatlas.io/vocab/hp#' + hpo_asct_kidney_edges['Property'].str.replace(' ', '_')
hpo_asct_kidney_edges['source'] = 'https://purl.humanatlas.io/vocab/hp'

/var/folders/td/20m4wtg53gv649fvblc4r7sc0000gn/T/ipykernel_75933/3197106429.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hpo_asct_kidney_edges['predicate'] = 'https://purl.humanatlas.io/vocab/hp#' + hpo_asct_kidney_edges['Property'].str.replace(' ', '_')
/var/folders/td/20m4wtg53gv649fvblc4r7sc0000gn/T/ipykernel_75933/3197106429.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hpo_asct_kidney_edges['source'] = 'https://purl.humanatlas.io/vocab/hp'

In [26]:
hpo_asct_kidney_edges.drop(columns=['Property'], inplace=True)
hpo_asct_kidney_edges.columns = ['subject', 'object', 'predicate', 'source' ]

hpo_asct_kidney_edges.reindex(['subject', 'predicate', 'object', 'source' ], axis=1)

/var/folders/td/20m4wtg53gv649fvblc4r7sc0000gn/T/ipykernel_75933/3600007528.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hpo_asct_kidney_edges.drop(columns=['Property'], inplace=True)

,subject,predicate,object,source
1,http://purl.obolibrary.org/obo/HP_0000003,https://purl.humanatlas.io/vocab/hp#part_of,http://purl.obolibrary.org/obo/UBERON_0002113,https://purl.humanatlas.io/vocab/hp
2,http://purl.obolibrary.org/obo/HP_0000003,https://purl.humanatlas.io/vocab/hp#characteri...,http://purl.obolibrary.org/obo/UBERON_0002113,https://purl.humanatlas.io/vocab/hp
3,http://purl.obolibrary.org/obo/HP_0000003,https://purl.humanatlas.io/vocab/hp#characteri...,http://purl.obolibrary.org/obo/UBERON_0011143,https://purl.humanatlas.io/vocab/hp
4,http://purl.obolibrary.org/obo/HP_0000003,https://purl.humanatlas.io/vocab/hp#characteri...,http://purl.obolibrary.org/obo/UBERON_0001008,https://purl.humanatlas.io/vocab/hp
12,http://purl.obolibrary.org/obo/HP_0000009,https://purl.humanatlas.io/vocab/hp#characteri...,http://purl.obolibrary.org/obo/UBERON_0001255,https://purl.humanatlas.io/vocab/hp
...,...,...,...,...
121367,http://purl.obolibrary.org/obo/HP_6001294,https://purl.humanatlas.io/vocab/hp#characteri...,http://purl.obolibrary.org/obo/UBERON_0011143,https://purl.humanatlas.io/vocab/hp
121368,http://purl.obolibrary.org/obo/HP_6001294,https://purl.humanatlas.io/vocab/hp#characteri...,http://purl.obolibrary.org/obo/UBERON_0001008,https://purl.humanatlas.io/vocab/hp
121618,http://purl.obolibrary.org/obo/HP_6001336,https://purl.humanatlas.io/vocab/hp#characteri...,http://purl.obolibrary.org/obo/UBERON_0002113,https://purl.humanatlas.io/vocab/hp
121619,http://purl.obolibrary.org/obo/HP_6001336,https://purl.humanatlas.io/vocab/hp#characteri...,http://purl.obolibrary.org/obo/UBERON_0011143,https://purl.humanatlas.io/vocab/hp
121620,http://purl.obolibrary.org/obo/HP_6001336,https://purl.humanatlas.io/vocab/hp#characteri...,http://purl.obolibrary.org/obo/UBERON_0001008,https://purl.humanatlas.io/vocab/hp

In [27]:
hpo_asct_kidney_edges.to_csv('../../data/outputs/hpo-asct-kidney-edges.csv', index=False)

### now, create a nodes table for the uberon terms:

In [28]:
all_uberon_xlinks_kidney

,HPO_IRI,HPO_Label,Property,Filler_IRI,Filler_Label,Obsolete,Replacement_IRI,Replacement_Label
1,http://purl.obolibrary.org/obo/HP_0000003,Multicystic kidney dysplasia,part of,http://purl.obolibrary.org/obo/UBERON_0002113,kidney,False,NaN,NaN
2,http://purl.obolibrary.org/obo/HP_0000003,Multicystic kidney dysplasia,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0002113,kidney,False,NaN,NaN
3,http://purl.obolibrary.org/obo/HP_0000003,Multicystic kidney dysplasia,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0011143,upper urinary tract,False,NaN,NaN
4,http://purl.obolibrary.org/obo/HP_0000003,Multicystic kidney dysplasia,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0001008,renal system,False,NaN,NaN
12,http://purl.obolibrary.org/obo/HP_0000009,Functional abnormality of the bladder,characteristic of,http://purl.obolibrary.org/obo/UBERON_0001255,urinary bladder,False,NaN,NaN
...,...,...,...,...,...,...,...,...
121367,http://purl.obolibrary.org/obo/HP_6001294,Tubular accumulation of uromodulin,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0011143,upper urinary tract,False,NaN,NaN
121368,http://purl.obolibrary.org/obo/HP_6001294,Tubular accumulation of uromodulin,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0001008,renal system,False,NaN,NaN
121618,http://purl.obolibrary.org/obo/HP_6001336,Hairy kidney sign,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0002113,kidney,False,NaN,NaN
121619,http://purl.obolibrary.org/obo/HP_6001336,Hairy kidney sign,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0011143,upper urinary tract,False,NaN,NaN
121620,http://purl.obolibrary.org/obo/HP_6001336,Hairy kidney sign,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0001008,renal system,False,NaN,NaN

In [29]:
hpo_kidney_as_nodes = all_uberon_xlinks_kidney[['Filler_IRI', 'Filler_Label']]
hpo_kidney_as_nodes['type'] = 'http://purl.obolibrary.org/obo/UBERON_0000061' # UBERON term for anatomical structure
hpo_kidney_as_nodes['source'] = 'https://purl.humanatlas.io/vocab/hp'
hpo_kidney_as_nodes.columns = ['iri', 'label', 'type', 'source']
hpo_kidney_as_nodes.head()
hpo_kidney_as_nodes.to_csv('../../data/outputs/hpo-kidney-as-nodes.csv', index=False)

/var/folders/td/20m4wtg53gv649fvblc4r7sc0000gn/T/ipykernel_75933/1440206578.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hpo_kidney_as_nodes['type'] = 'http://purl.obolibrary.org/obo/UBERON_0000061' # UBERON term for anatomical structure
/var/folders/td/20m4wtg53gv649fvblc4r7sc0000gn/T/ipykernel_75933/1440206578.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hpo_kidney_as_nodes['source'] = 'https://purl.humanatlas.io/vocab/hp'

### CL links

In [30]:
all_cl_xlinks = pd.read_csv('../../data/outputs/hpo_to_cl_links.csv')
all_cl_xlinks.head()

,HPO_IRI,HPO_Label,Property,Filler_IRI,Filler_Label,Obsolete,Replacement_IRI,Replacement_Label
0,http://purl.obolibrary.org/obo/HP_0000027,Azoospermia,develops from,http://purl.obolibrary.org/obo/CL_0000018,spermatid,False,NaN,NaN
1,http://purl.obolibrary.org/obo/HP_0000235,Abnormal cranial suture/fontanelle morphology,has part,http://purl.obolibrary.org/obo/CL_0000000,cell,False,NaN,NaN
2,http://purl.obolibrary.org/obo/HP_0000235,Abnormal cranial suture/fontanelle morphology,has part,http://purl.obolibrary.org/obo/CL_0002320,connective tissue cell,False,NaN,NaN
3,http://purl.obolibrary.org/obo/HP_0000236,Abnormal anterior fontanelle morphology,has part,http://purl.obolibrary.org/obo/CL_0000000,cell,False,NaN,NaN
4,http://purl.obolibrary.org/obo/HP_0000236,Abnormal anterior fontanelle morphology,has part,http://purl.obolibrary.org/obo/CL_0002320,connective tissue cell,False,NaN,NaN

In [31]:
len(all_cl_xlinks['Filler_IRI'].unique())

87

In [32]:
all_cl_xlinks

,HPO_IRI,HPO_Label,Property,Filler_IRI,Filler_Label,Obsolete,Replacement_IRI,Replacement_Label
0,http://purl.obolibrary.org/obo/HP_0000027,Azoospermia,develops from,http://purl.obolibrary.org/obo/CL_0000018,spermatid,False,NaN,NaN
1,http://purl.obolibrary.org/obo/HP_0000235,Abnormal cranial suture/fontanelle morphology,has part,http://purl.obolibrary.org/obo/CL_0000000,cell,False,NaN,NaN
2,http://purl.obolibrary.org/obo/HP_0000235,Abnormal cranial suture/fontanelle morphology,has part,http://purl.obolibrary.org/obo/CL_0002320,connective tissue cell,False,NaN,NaN
3,http://purl.obolibrary.org/obo/HP_0000236,Abnormal anterior fontanelle morphology,has part,http://purl.obolibrary.org/obo/CL_0000000,cell,False,NaN,NaN
4,http://purl.obolibrary.org/obo/HP_0000236,Abnormal anterior fontanelle morphology,has part,http://purl.obolibrary.org/obo/CL_0002320,connective tissue cell,False,NaN,NaN
...,...,...,...,...,...,...,...,...
5264,http://purl.obolibrary.org/obo/HP_6001307,Fractured trapezium bone,has part,http://purl.obolibrary.org/obo/CL_0000000,cell,False,NaN,NaN
5265,http://purl.obolibrary.org/obo/HP_6001308,Fractured trapezoid bone,has part,http://purl.obolibrary.org/obo/CL_0000000,cell,False,NaN,NaN
5266,http://purl.obolibrary.org/obo/HP_6001309,Fractured capitate bone,has part,http://purl.obolibrary.org/obo/CL_0000000,cell,False,NaN,NaN
5267,http://purl.obolibrary.org/obo/HP_6001310,Fractured hamate bone,has part,http://purl.obolibrary.org/obo/CL_0000000,cell,False,NaN,NaN
5268,http://purl.obolibrary.org/obo/HP_6001314,Reduced erythrocyte glutathione peroxidase,characteristic of part of,http://purl.obolibrary.org/obo/CL_0000232,erythrocyte,False,NaN,NaN

In [33]:
cl_Filler_Label_df = all_cl_xlinks['Filler_Label'].to_frame().drop_duplicates().reset_index(drop=True)
cl_Filler_Label_df.to_csv('../../data/outputs/hpo_to_cl_links_unique_filler_labels.csv', index=False)

### unfortunately currently we don't have any matching CL terms specific to kidney, we will be working on adding HPO CL terms.